FROM node:8

RUN apt-get update \
    && apt-get install -y nginx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && echo "daemon off;" >> /etc/nginx/nginx.conf \
    && npm run build

ADD default /etc/nginx/sites-available/default

COPY dist /usr/share/nginx/html

COPY ssl/ /etc/ssl/private/

EXPOSE 80 443
CMD ["nginx"]